name: "Hello"

on:
 pull_request:
    types:
      - opened
      - closed
  #workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          gh-token: ${{secrets.GH_TOKEN}}
          label: "needs-review"